/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as OrderWorkflowRouteImport } from './routes/order-workflow'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRestaurantsRouteImport } from './routes/api/restaurants'
import { Route as ApiRestaurantsRestaurantIdOrdersRouteImport } from './routes/api/restaurants.$restaurantId.orders'
import { Route as ApiRestaurantsRestaurantIdMenuRouteImport } from './routes/api/restaurants.$restaurantId.menu'
import { Route as ApiOrdersOrderIdPrepareRouteImport } from './routes/api/orders.$orderId.prepare'

const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderWorkflowRoute = OrderWorkflowRouteImport.update({
  id: '/order-workflow',
  path: '/order-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRestaurantsRoute = ApiRestaurantsRouteImport.update({
  id: '/api/restaurants',
  path: '/api/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRestaurantsRestaurantIdOrdersRoute =
  ApiRestaurantsRestaurantIdOrdersRouteImport.update({
    id: '/$restaurantId/orders',
    path: '/$restaurantId/orders',
    getParentRoute: () => ApiRestaurantsRoute,
  } as any)
const ApiRestaurantsRestaurantIdMenuRoute =
  ApiRestaurantsRestaurantIdMenuRouteImport.update({
    id: '/$restaurantId/menu',
    path: '/$restaurantId/menu',
    getParentRoute: () => ApiRestaurantsRoute,
  } as any)
const ApiOrdersOrderIdPrepareRoute = ApiOrdersOrderIdPrepareRouteImport.update({
  id: '/api/orders/$orderId/prepare',
  path: '/api/orders/$orderId/prepare',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kitchen': typeof KitchenRoute
  '/order-workflow': typeof OrderWorkflowRoute
  '/restaurant': typeof RestaurantRoute
  '/api/restaurants': typeof ApiRestaurantsRouteWithChildren
  '/api/orders/$orderId/prepare': typeof ApiOrdersOrderIdPrepareRoute
  '/api/restaurants/$restaurantId/menu': typeof ApiRestaurantsRestaurantIdMenuRoute
  '/api/restaurants/$restaurantId/orders': typeof ApiRestaurantsRestaurantIdOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kitchen': typeof KitchenRoute
  '/order-workflow': typeof OrderWorkflowRoute
  '/restaurant': typeof RestaurantRoute
  '/api/restaurants': typeof ApiRestaurantsRouteWithChildren
  '/api/orders/$orderId/prepare': typeof ApiOrdersOrderIdPrepareRoute
  '/api/restaurants/$restaurantId/menu': typeof ApiRestaurantsRestaurantIdMenuRoute
  '/api/restaurants/$restaurantId/orders': typeof ApiRestaurantsRestaurantIdOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kitchen': typeof KitchenRoute
  '/order-workflow': typeof OrderWorkflowRoute
  '/restaurant': typeof RestaurantRoute
  '/api/restaurants': typeof ApiRestaurantsRouteWithChildren
  '/api/orders/$orderId/prepare': typeof ApiOrdersOrderIdPrepareRoute
  '/api/restaurants/$restaurantId/menu': typeof ApiRestaurantsRestaurantIdMenuRoute
  '/api/restaurants/$restaurantId/orders': typeof ApiRestaurantsRestaurantIdOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kitchen'
    | '/order-workflow'
    | '/restaurant'
    | '/api/restaurants'
    | '/api/orders/$orderId/prepare'
    | '/api/restaurants/$restaurantId/menu'
    | '/api/restaurants/$restaurantId/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kitchen'
    | '/order-workflow'
    | '/restaurant'
    | '/api/restaurants'
    | '/api/orders/$orderId/prepare'
    | '/api/restaurants/$restaurantId/menu'
    | '/api/restaurants/$restaurantId/orders'
  id:
    | '__root__'
    | '/'
    | '/kitchen'
    | '/order-workflow'
    | '/restaurant'
    | '/api/restaurants'
    | '/api/orders/$orderId/prepare'
    | '/api/restaurants/$restaurantId/menu'
    | '/api/restaurants/$restaurantId/orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KitchenRoute: typeof KitchenRoute
  OrderWorkflowRoute: typeof OrderWorkflowRoute
  RestaurantRoute: typeof RestaurantRoute
  ApiRestaurantsRoute: typeof ApiRestaurantsRouteWithChildren
  ApiOrdersOrderIdPrepareRoute: typeof ApiOrdersOrderIdPrepareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-workflow': {
      id: '/order-workflow'
      path: '/order-workflow'
      fullPath: '/order-workflow'
      preLoaderRoute: typeof OrderWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/restaurants': {
      id: '/api/restaurants'
      path: '/api/restaurants'
      fullPath: '/api/restaurants'
      preLoaderRoute: typeof ApiRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/restaurants/$restaurantId/orders': {
      id: '/api/restaurants/$restaurantId/orders'
      path: '/$restaurantId/orders'
      fullPath: '/api/restaurants/$restaurantId/orders'
      preLoaderRoute: typeof ApiRestaurantsRestaurantIdOrdersRouteImport
      parentRoute: typeof ApiRestaurantsRoute
    }
    '/api/restaurants/$restaurantId/menu': {
      id: '/api/restaurants/$restaurantId/menu'
      path: '/$restaurantId/menu'
      fullPath: '/api/restaurants/$restaurantId/menu'
      preLoaderRoute: typeof ApiRestaurantsRestaurantIdMenuRouteImport
      parentRoute: typeof ApiRestaurantsRoute
    }
    '/api/orders/$orderId/prepare': {
      id: '/api/orders/$orderId/prepare'
      path: '/api/orders/$orderId/prepare'
      fullPath: '/api/orders/$orderId/prepare'
      preLoaderRoute: typeof ApiOrdersOrderIdPrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiRestaurantsRouteChildren {
  ApiRestaurantsRestaurantIdMenuRoute: typeof ApiRestaurantsRestaurantIdMenuRoute
  ApiRestaurantsRestaurantIdOrdersRoute: typeof ApiRestaurantsRestaurantIdOrdersRoute
}

const ApiRestaurantsRouteChildren: ApiRestaurantsRouteChildren = {
  ApiRestaurantsRestaurantIdMenuRoute: ApiRestaurantsRestaurantIdMenuRoute,
  ApiRestaurantsRestaurantIdOrdersRoute: ApiRestaurantsRestaurantIdOrdersRoute,
}

const ApiRestaurantsRouteWithChildren = ApiRestaurantsRoute._addFileChildren(
  ApiRestaurantsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KitchenRoute: KitchenRoute,
  OrderWorkflowRoute: OrderWorkflowRoute,
  RestaurantRoute: RestaurantRoute,
  ApiRestaurantsRoute: ApiRestaurantsRouteWithChildren,
  ApiOrdersOrderIdPrepareRoute: ApiOrdersOrderIdPrepareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
